export const LLM_DEFAULTS = {
  TIMEOUT: 60000,
  BATCH_SIZE: 10,
  BATCH_DELAY: 500,
  TEMPERATURE: 0.3,
  MAX_RETRIES: 2,
  CACHE_TTL: 300000,
  CACHE_MAX_SIZE: 100,
  RATE_LIMIT_MAX_TOKENS: 100,
  RATE_LIMIT_REFILL_RATE: 10,
  RATE_LIMIT_REFILL_INTERVAL: 1000,
  STREAMING_TIMEOUT: 120000,
} as const

export const LLM_MODELS = {
  DEFAULT: 'gpt-4o-mini',
  FALLBACK: 'gpt-3.5-turbo',
} as const

export const TOPIC_ANALYSIS = {
  MIN_MATCH_SCORE: 70,
  MAX_ITEMS: 10,
  TIME_RANGE_HOURS: 24,
} as const
